theme: jekyll-theme-tactile
about me: Hi, my name is Adrian. I am a computer science student at Clemson Unversity. I love working on frontend development, software development and hopefully creating something that makes people smile
